name: co_works
description: "This is a flutter app for booking rooms and workspace"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  go_router: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true